# Generated by Django 5.1.6 on 2025-03-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_categoria_quiz_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to='quiz_images/'),
        ),
    ]
